- name: Set Avahi hostname resolution
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns'
    backup: yes

- name: Stop and disable systemd-resolved.service
  systemd:
    name: systemd-resolved.service
    enabled: false
    state: stopped

- name: Start and enable avahi-daemon.service
  systemd:
    name: avahi-daemon.service
    enabled: true
    state: started
