---

- name: Install Docker and Docker Compose
  pacman:
    name:
      - docker
      - docker-compose
      - python-docker
    state: present

- name: Start Nextcloud with Docker Compose
  docker_compose:
    project_name: nextcloud
    definition:
      version: '3.7'

      services:
        db:
          image: postgres
          restart: always
          volumes:
            - db:/var/lib/postgresql/data
          environment:
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=admin
            - "POSTGRES_PASSWORD={{ nextcloud_postgres_password }}"

        app:
          image: nextcloud
          restart: always
          ports:
            - 8080:80
          volumes:
            - nextcloud:/var/www/html
          environment:
            - POSTGRES_HOST=db
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=admin
            - "POSTGRES_PASSWORD={{ nextcloud_postgres_password }}"
            - "NEXTCLOUD_ADMIN_PASSWORD={{ nextcloud_admin_password }}"
            - NEXTCLOUD_ADMIN_USER=admin
            - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.egidiocaprino.com
          depends_on:
            - db

      volumes:
        db:
        nextcloud:

- name: Copy Nextcloud custom configuration file
  copy:
    src: custom.config.php
    dest: /tmp/custom.config.php

- name: Copy Nextcloud custom configuration file inside the container
  command: docker cp /tmp/custom.config.php nextcloud_app_1:/var/www/html/config/custom.config.php

- name: Restart Docker container
  command: docker restart nextcloud_app_1
