---
- name: Update the system
  pacman:
    update_cache: yes
    upgrade: yes
  register: system_update

- name: Reboot the server
  reboot:
  when: system_update.changed

- name: Install Docker and Docker Compose
  pacman:
    name:
      - docker
      - docker-compose
      - python-docker
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker.service
    state: started
    enabled: yes
