- name: Install Docker and Docker Compose
  pacman:
    name:
      - docker
      - docker-compose
      - python-docker
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker.service
    state: started
    enabled: yes
